-- this file is generated using lunr discord.gg/9yAtRgpsua

local table_0xbd9 = game:GetService("table: 0xbd9")
local table_0xbd91 = game:GetService("table: 0xbd9")
local table_0xbd92 = game:GetService("table: 0xbd9")
local LocalPlayer = table_0xbd9.LocalPlayer
local RtxPvPHelper = table_0xbd92:FindFirstChild("RtxPvPHelper")
local Destroy = object:Destroy()
local ScreenGui = Instance.new("ScreenGui")
ScreenGui.Name = "RtxPvPHelper"
ScreenGui.Parent = table_0xbd92
ScreenGui.ResetOnSpawn = false
local Frame = Instance.new("Frame")
Frame.Size = UDim2.new(0, 230, 0, 180)
Frame.Position = UDim2.new(0.5, -115, 0.5, -90)
Frame.BackgroundColor3 = Color3.fromRGB(15, 15, 15)
Frame.BorderSizePixel = 0
Frame.Active = true
Frame.Draggable = true
Frame.Parent = ScreenGui
local UICorner = Instance.new("UICorner")
UICorner.CornerRadius = UDim.new(0, 10)
UICorner.Parent = Frame
local UIStroke = Instance.new("UIStroke")
UIStroke.Thickness = 2
UIStroke.Color = Color3.fromRGB(255, 255, 255)
UIStroke.Parent = Frame
local TextLabel = Instance.new("TextLabel")
TextLabel.Text = "Rtx PvP Helper"
TextLabel.Font = Enum.Font.GothamBold
TextLabel.TextSize = 20
TextLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
TextLabel.BackgroundTransparency = 1
TextLabel.Size = UDim2.new(1, 0, 0, 26)
TextLabel.Parent = Frame
local TextLabel3 = Instance.new("TextLabel")
TextLabel3.Text = "Anti Ragdoll"
TextLabel3.Font = Enum.Font.GothamSemibold
TextLabel3.TextSize = 16
TextLabel3.TextColor3 = Color3.fromRGB(255, 255, 255)
TextLabel3.BackgroundTransparency = 1
TextLabel3.Position = UDim2.new(0.05, 0, 0.18, 0)
TextLabel3.Size = UDim2.new(0, 130, 0, 24)
TextLabel3.TextXAlignment = Enum.TextXAlignment.Left
TextLabel3.Parent = Frame
local TextLabel4 = Instance.new("TextLabel")
TextLabel4.Text = "Hitbox"
TextLabel4.Font = Enum.Font.GothamSemibold
TextLabel4.TextSize = 16
TextLabel4.TextColor3 = Color3.fromRGB(255, 255, 255)
TextLabel4.BackgroundTransparency = 1
TextLabel4.Position = UDim2.new(0.05, 0, 0.44, 0)
TextLabel4.Size = UDim2.new(0, 130, 0, 24)
TextLabel4.TextXAlignment = Enum.TextXAlignment.Left
TextLabel4.Parent = Frame
local TextLabel5 = Instance.new("TextLabel")
TextLabel5.Text = "Auto Hit"
TextLabel5.Font = Enum.Font.GothamSemibold
TextLabel5.TextSize = 16
TextLabel5.TextColor3 = Color3.fromRGB(255, 255, 255)
TextLabel5.BackgroundTransparency = 1
TextLabel5.Position = UDim2.new(0.05, 0, 0.7, 0)
TextLabel5.Size = UDim2.new(0, 130, 0, 24)
TextLabel5.TextXAlignment = Enum.TextXAlignment.Left
TextLabel5.Parent = Frame
local Frame6 = Instance.new("Frame")
Frame6.Size = UDim2.new(0, 50, 0, 20)
Frame6.Position = UDim2.new(0.75, 0, 0.18, 0)
Frame6.BackgroundColor3 = Color3.fromRGB(255, 0, 0)
Frame6.BorderSizePixel = 0
Frame6.Parent = Frame
local UICorner7 = Instance.new("UICorner")
UICorner7.CornerRadius = UDim.new(1, 0)
UICorner7.Parent = Frame6
local Frame8 = Instance.new("Frame")
Frame8.Size = UDim2.new(0, 18, 0, 18)
Frame8.Position = UDim2.new(0.05, 0, 0.05, 0)
Frame8.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Frame8.BorderSizePixel = 0
Frame8.Parent = Frame6
local UICorner9 = Instance.new("UICorner")
UICorner9.CornerRadius = UDim.new(1, 0)
UICorner9.Parent = Frame8
local Frame10 = Instance.new("Frame")
Frame10.Size = UDim2.new(0, 50, 0, 20)
Frame10.Position = UDim2.new(0.75, 0, 0.44, 0)
Frame10.BackgroundColor3 = Color3.fromRGB(255, 0, 0)
Frame10.BorderSizePixel = 0
Frame10.Parent = Frame
local UICorner11 = Instance.new("UICorner")
UICorner11.CornerRadius = UDim.new(1, 0)
UICorner11.Parent = Frame10
local Frame12 = Instance.new("Frame")
Frame12.Size = UDim2.new(0, 18, 0, 18)
Frame12.Position = UDim2.new(0.05, 0, 0.05, 0)
Frame12.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Frame12.BorderSizePixel = 0
Frame12.Parent = Frame10
local UICorner13 = Instance.new("UICorner")
UICorner13.CornerRadius = UDim.new(1, 0)
UICorner13.Parent = Frame12
local Frame14 = Instance.new("Frame")
Frame14.Size = UDim2.new(0, 50, 0, 20)
Frame14.Position = UDim2.new(0.75, 0, 0.7, 0)
Frame14.BackgroundColor3 = Color3.fromRGB(255, 0, 0)
Frame14.BorderSizePixel = 0
Frame14.Parent = Frame
local UICorner15 = Instance.new("UICorner")
UICorner15.CornerRadius = UDim.new(1, 0)
UICorner15.Parent = Frame14
local Frame16 = Instance.new("Frame")
Frame16.Size = UDim2.new(0, 18, 0, 18)
Frame16.Position = UDim2.new(0.05, 0, 0.05, 0)
Frame16.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Frame16.BorderSizePixel = 0
Frame16.Parent = Frame14
local UICorner17 = Instance.new("UICorner")
UICorner17.CornerRadius = UDim.new(1, 0)
UICorner17.Parent = Frame16
local conn = Frame6.InputBegan:Connect(function(input, gameProcessed)
end)
local conn18 = Frame10.InputBegan:Connect(function(input, gameProcessed)
end)
local conn19 = Frame14.InputBegan:Connect(function(input, gameProcessed)
end)
local TextButton = Instance.new("TextButton")
TextButton.Size = UDim2.new(0.9, 0, 0, 26)
TextButton.Position = UDim2.new(0.05, 0, 0.86, 0)
TextButton.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
TextButton.Text = "Tp Hit"
TextButton.TextColor3 = Color3.fromRGB(255, 255, 255)
TextButton.Font = Enum.Font.GothamSemibold
TextButton.TextSize = 15
TextButton.Parent = Frame
local UICorner20 = Instance.new("UICorner")
UICorner20.CornerRadius = UDim.new(0, 6)
UICorner20.Parent = TextButton
local conn21 = TextButton.MouseButton1Click:Connect(function()
    local HumanoidRootPart = object:FindFirstChild("HumanoidRootPart")
end)
local HumanoidRootPart23 = object:FindFirstChild("HumanoidRootPart")
local Humanoid = object:FindFirstChildOfClass("Humanoid")
local conn22 = table_0xbd91.Heartbeat:Connect(function(deltaTime)
    local HumanoidRootPart24 = object:FindFirstChild("HumanoidRootPart")
    local Humanoid25 = object:FindFirstChildOfClass("Humanoid")
end)
